### ISSUE TITLE
We need to simplify the way we deal with datasets

### ISSUE THREAD

**Issue by tian-chaiyaporn** [tian-chaiyaporn/thinkful-capstone-1#1]
Our app is already a bit complicated. We need to get data from API, store on a browser-based cache (locaStorage) to avoid API limitations, deal with this data on memory, etc. Also, we deal with states and neighborhoods which are identifies by code, etc. - so we need to make it pretty simple to deal with those data together, so the app can evolve with complex functionalities in the future without making us lose some hair 😂

**Comment by tian-chaiyaporn** [comment]
@joelwallis ^

**Comment by joeljuca** [comment]
We are already discussing this on #2.
